services:
  postgres:
    image: postgres:16
    container_name: todo-postgres
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_pass
      POSTGRES_INITDB_ARGS: --encoding=UTF8 --lc-collate=C.UTF-8 --lc-ctype=C.UTF-8
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  api:
    build: .
    ports:
      - "4567:4567"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=todo_user
      - DB_PASSWORD=todo_pass
      - DB_NAME=todo_db
    depends_on:
      - postgres
volumes:
  postgres_data:

  