info:
  contact: {}
paths:
  /api/v1/auth/login:
    post:
      consumes:
      - application/json
      description: 登录成功返回 JWT Token
      produces:
      - application/json
      responses:
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 用户登录
      tags:
      - 认证
swagger: "2.0"
